"start" = 0x80006310;
"_Z12lbl_80120d80v" = 0x80120d80;
"_Z14loadScopedDataIjEPT_P21ExplicitScopedPointerIS0_E" = 0x8017c9d8;
"_ZN9Component14loadProtagInfoEPj" = 0x8023f2f4;
"_ZN10Intangible16updateFlashCycleEv" = 0x8034f8f0;
"_ZN7Ability14hasUniqueGuardEv" = 0x804d2cb4;
"_Z12lbl_804eda6cP4Hero" = 0x804eda6c;
"_ZN8Grounded15getGroundedDataEP4Hero" = 0x804eda94;
"getInputData" = 0x804edae4;
"_ZN6Effect13getEffectDataEP4Hero" = 0x804edaf4;
"_ZN7Ability14getAbilityDataEP4Hero" = 0x804edb0c;
"_ZN10Invincible13getInvincDataEP4Hero" = 0x804edb1c;
/* "_ZN12MutableArrayIP4HeroLj4EEixEj" = 0x804f4908; */

"gMainPointer" = 0x809ed108;
